### ISSUE TITLE
pcl 1.7 openni2 problem and pcl filter

### ISSUE THREAD

**Issue by nallezard** [Xamla/torch-pcl#2]
Hi Andreas
i'm testing your pcl binding for torch
i'm using pcl 1.7 and there is no openni2 headers in this version so the compile process stalls in openni2.cpp and OpenNI2GrabberStream.h...
so i removed all the reference to openni2 in the code but is there a better way to compile with the 1.7 version?

I see that you have made c wrappers for basic filtering, but not the lua part, do you plane to do this in a short future or i have to do it by myself?

thanks
Nicolas

**Comment by andreaskoepf** [comment]
I started development with the prebuilt binaries providede form [pointcloud.org](http://www.pointclouds.org/downloads/linux.html). But lately since I am preparing some experiments with the structure.io sensor which has a depth-only stream I am using the latest pcl source version ([support](https://github.com/PointCloudLibrary/pcl/pull/1372) for OpenNI devices that do not deliver RGB data has been merged only some weeks ago).

The inital version of the OpenNIGrapper was added to pcl on 17 Feb 2014. Since PCL-1.7.1 was released  Oct 2013 it is unfortunately not part of it.

Are there any reasons why you cannot use a newer PCL? Since I plan to use my wrapper for the next years I am primarily focussing on the future (e.g. backward-compatibility is less important for me). 

In general the pcl wrapper should become more complete (at least cover most basic functionality) over the next month. You found this project in a really early stage .. e.g. there will be much more error checking and many more pcl algorithms. Filtering will be available from lua soon.

**Comment by andreaskoepf** [comment]
@nallezard It would be great if you could tell me which PCL functionality is most important for you. This helps me to set some priorities for the wrapper.

**Comment by nallezard** [comment]
ok i understand your reasons and i agree that  backward-compatibility is less important than the future versions.
no, i got any strong reasons to keep the 1.7 but this version works for me and i didn't have to change until now.

for me the most important functionalities are filtering, segmentation, features matching/registration and visualizer callback. 

anyway it's great to use pcl with torch/lua. 
I've studied your code a lit bit and maybe i can help with my modest capabilities and free time to wraps some more functionalities.

**Comment by andreaskoepf** [comment]
@nallezard Any help is welcome. :-) If you like to discuss some details you can reach me via gitter in [Xamla/Contributors](https://gitter.im/Xamla/contributors).

btw A first batch of [simple filters](https://github.com/Xamla/torch-pcl/blob/master/filter.lua) is now available.

**Comment by andreaskoepf** [comment]
For the time being we only support the github master branch head version.
